/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModuleRouteImport } from './routes/$module'
import { Route as PorteriaRouteImport } from './routes/porteria'
import { Route as ResidenteRouteImport } from './routes/residente'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleRoute = ModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const PorteriaRoute = PorteriaRouteImport.update({
  id: '/porteria',
  path: '/porteria',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidenteRoute = ResidenteRouteImport.update({
  id: '/residente',
  path: '/residente',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$module': typeof ModuleRoute
  '/porteria': typeof PorteriaRoute
  '/residente': typeof ResidenteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$module': typeof ModuleRoute
  '/porteria': typeof PorteriaRoute
  '/residente': typeof ResidenteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$module': typeof ModuleRoute
  '/porteria': typeof PorteriaRoute
  '/residente': typeof ResidenteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$module' | '/porteria' | '/residente'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$module' | '/porteria' | '/residente'
  id: '__root__' | '/' | '/$module' | '/porteria' | '/residente'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModuleRoute: typeof ModuleRoute
  PorteriaRoute: typeof PorteriaRoute
  ResidenteRoute: typeof ResidenteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$module': {
      id: '/$module'
      path: '/$module'
      fullPath: '/$module'
      preLoaderRoute: typeof ModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/porteria': {
      id: '/porteria'
      path: '/porteria'
      fullPath: '/porteria'
      preLoaderRoute: typeof PorteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residente': {
      id: '/residente'
      path: '/residente'
      fullPath: '/residente'
      preLoaderRoute: typeof ResidenteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModuleRoute: ModuleRoute,
  PorteriaRoute: PorteriaRoute,
  ResidenteRoute: ResidenteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
